### ISSUE TITLE
Iterator direction

### ISSUE THREAD

**Issue by valmirjunior0088** [YaLTeR/circular-queue#2]
Is there some specific reason why you `.rev()` each half of the iterator separately?

Also, is there a way to get the other direction (oldest to newest) without having to `.rev()` the iterator each time it is used? Perhaps you could add an iterator like the following:

```
let (first_half, second_half) = self.data.split_at(self.insertion_index);
second_half.iter().chain(first_half.iter())
```

**Comment by YaLTeR** [comment]
> Is there some specific reason why you `.rev()` each half of the iterator separately?

I suppose that part can be rewritten as `b.iter().chain(a.iter()).rev()`, yeah. Unfortunately, that would be a breaking change as I chose to use an explicitly specified type alias for the iterator type rather than a newtype (for no particular reason), so I think I'd rather avoid chaging it unless there's a good justification.

> Also, is there a way to get the other direction (oldest to newest) without having to `.rev()` the iterator each time it is used? Perhaps you could add an iterator like the following:
> 
> ```
> let (first_half, second_half) = self.data.split_at(self.insertion_index);
> second_half.iter().chain(first_half.iter())
> ```

Sure, that should work. The usual method could even be implemented in terms of this one, then, assuming a breaking change was made. But since I'd like no breaking changes, this could just be a separate method. Could you send a PR?

**Comment by valmirjunior0088** [comment]
Since you don't want a breaking change, what would you suggest the new function name be? I'm having a hard time thinking of one.
